apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-app
  template:
    metadata:
      labels:
        app: stock-app
    spec:
      containers:
        - name: stock-app-container
          image: your-image-name
          ports:
            - containerPort: 8080
